baseURL: "https://torgeiraamboe.github.io/"
title: Torgeir Aambø
paginate: 10
theme: PaperMod
copyright: " "
publishDir: docs

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true



    
outputs:
    home:
        - HTML
        - RSS
        - JSON

menu:
    main:
      - name: Research
        url: research/
        weight: 5
      - name: Blog
        url: posts/
        weight: 6  
      - name: Outreach
        url: "outreach/"
        weight: 10
      - name: Reading
        url: have-read/
        weight: 15      
      - name: About
        url: about/
        weight: 30



params:
    env: production
    description: " "
    author: "Torgeir Aambø"
    authors:
        - "Torgeir Aambø"

    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    showtoc: false
    math: true
    hideAuthor: true
    # comments: false
    # images: ["papermod-cover.png"]

    profileMode:
          enabled: true
          title: Torgeir Aambø, PhD
          imageUrl: "TOAAM.jpg"
          # imageTitle: my image
          imageWidth: 370
          imageHeight: 380
          subtitle: "Researcher in Operations Research at FFI"

    social:
        facebook_admin: " "

    socialIcons:
        #- name: LinkedIn
        #  url: "https://www.linkedin.com/in/torgeir-aamb%C3%B8/"
        #- name: Github
        #  url: "https://github.com/torgeiraamboe"
        #- name: ORCID
        #  url: "https://orcid.org/0000-0002-9975-5520"
        #- name: ArXiv
        #  url: "https://arxiv.org/search/math?searchtype=author&query=Aamb%C3%B8%2C+T"          
        #- name: Email
        #  url: "mailto:torgeiraamboe@gmail.com"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
    #    hidden: true # hide everywhere but not in structured data
    #    hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]


taxonomies:
    category: categories
    tag: tags
    series: series

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - '\['
            - '\]'
          - - $$
            - $$
          inline:
          - - '\('
            - '\)'
          - - '$'
            - '$'
        enable: true
  

privacy:
    vimeo:
        disabled: false
        simple: true

    x:
        disabled: false
        enableDNT: false
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    x:
        disableInlineCSS: true

    